### ISSUE TITLE
Ping Dispatcher and Ping All Dispatchers Never Receive Responses

### ISSUE THREAD

**Issue by ianwknox** [NISystemsEngineering/AsynchronousMessageCommunication#6]
The ping functions will successfully send a ping message to a remote dispatcher, but the local dispatcher will never receive an acknowledgement message.

**Comment by mattwhitlock** [comment]
This is due to Send Message over UDP.vi using the computer name from Get Local Name and IP.vi rather than the IP address. Fixing and submitting pull request.

**Comment by smithed** [comment]
https://github.com/NISystemsEngineering/AsynchronousMessageCommunication/pull/7
